### ISSUE TITLE
Why the illuminant color in gray_card_illum_dict.mat is green channel normalized?

### ISSUE THREAD

**Issue by Blade6570** [SamsungLabs/day-to-night#4]
If I am working on RGB images, it creates greenish color for each illuminant. It would be great if the mat file has unnormalized values.

**Comment by abhijithpunnappurath** [comment]
The illuminant values in the mat file are normalized as [R/G, 1, B/G]. Perhaps I am misunderstanding your question, but an unnormalized illuminant value [R, G, B] will not change the color cast -- you will simply be multiplying all three color channels by the same scalar G.

The illuminant values in the mat file are applied to RAW images before they have been white-balanced, such that applying a diagonal correction removes the color cast due to the illuminant. They are not intended for use on sRGB images.

Please let me know if this answers your question.
